In [2]:
from google.colab import files
uploaded = files.upload()

Saving kaggle.json to kaggle.json

In [3]:
!mkdir -p ~/.kaggle
!mv kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [4]:
!kaggle competitions download -c titanic

Downloading titanic.zip to /content
  0% 0.00/34.1k [00:00<?, ?B/s]
100% 34.1k/34.1k [00:00<00:00, 56.7MB/s]

In [5]:
!unzip titanic.zip

Archive:  titanic.zip
  inflating: gender_submission.csv
  inflating: test.csv
  inflating: train.csv

In [21]:
import pandas as pd

titanic_data = pd.read_csv('train.csv')
titanic_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [22]:
#Create a copy of the dataframe. From now on we will use titanic_data_frame

titanic_data_frame = titanic_data.copy()

In [24]:
titanic_data_frame.info()
titanic_data_frame.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

🌟 Exercise 1: Duplicate Detection and Removal

In [25]:
titanic_data_frame = titanic_data_frame.drop_duplicates(subset = None, keep='first', inplace=False) #removes duplicated rows

In [26]:
titanic_data_frame.info() #verifying again number of rows looks good. No duplicates found!

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

🌟 Exercise 2: Handling Missing Values

In [27]:
titanic_data_frame.isnull().sum() #checking for missing values.

# The only important data that we need to fill would be age.
# Cabin is not so relevant

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

You may impute by doing a linear regression or by using another statistic approach such as mode, meadian or mean. We will choose to do a fill using the median values.

In [28]:
titanic_data_frame.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

We will add a feature called filled age for comparison reasons.

In [30]:
titanic_data_frame['filled_Age'] = titanic_data_frame['Age'].fillna(titanic_data_frame.groupby(['Pclass','Sex'])['Age'].transform('median'))

In [31]:
titanic_data_frame.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,filled_Age
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208,29.112424
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429,13.304424
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000,0.420000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400,21.500000
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200,26.000000
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000,36.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200,80.000000

🌟 Exercise 3: Feature Engineering

In [32]:
titanic_data_frame.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,filled_Age
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,22.0
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,38.0
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,26.0
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,35.0
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,35.0

In [42]:
titanic_data_frame['Parch'].unique()

array([0, 1, 2, 5, 3, 4, 6])

In [43]:
titanic_data_frame['SibSp'].unique()

array([1, 0, 3, 4, 2, 5, 8])

In [44]:
titanic_data_frame['FamilySize'] = titanic_data_frame['Parch'] + titanic_data_frame['SibSp']

Encoding for EX6 FYI

In [46]:
titanic_data_frame['Sex'].unique() #converting categorical values or qualitative values into quants
titanic_data_frame['Sex'] = titanic_data_frame['Sex'].map({'male':0, 'female':1}) #another method is to do a get_dummy

Exercise 4: Outlier Detection and Handling. We will use the IQR method

In [48]:
titanic_data_frame.describe()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,filled_Age,Family_Size,FamilySize
count,891.000000,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,0.352413,29.699118,0.523008,0.381594,32.204208,29.112424,0.799102,0.904602
std,257.353842,0.486592,0.836071,0.477990,14.526497,1.102743,0.806057,49.693429,13.304424,1.509163,1.613459
min,1.000000,0.000000,1.000000,0.000000,0.420000,0.000000,0.000000,0.000000,0.420000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,0.000000,20.125000,0.000000,0.000000,7.910400,21.500000,0.000000,0.000000
50%,446.000000,0.000000,3.000000,0.000000,28.000000,0.000000,0.000000,14.454200,26.000000,0.000000,0.000000
75%,668.500000,1.000000,3.000000,1.000000,38.000000,1.000000,0.000000,31.000000,36.000000,1.000000,1.000000
max,891.000000,1.000000,3.000000,1.000000,80.000000,8.000000,6.000000,512.329200,80.000000,10.000000,10.000000

In [49]:
 Q1 = titanic_data_frame[['Age', 'Fare']].quantile(0.25)
 Q3 = titanic_data_frame[['Age', 'Fare']].quantile(0.75)
 IQR = Q3 - Q1

titanic_data_frame = titanic_data_frame[~((titanic_data_frame[['Age', 'Fare']]< (Q1-1.5*IQR) | (titanic_data_frame[['Age', 'Fare']]> (Q3+ 1.5*IQR)))).any(axis=1)]

In [50]:
titanic_data_frame.info()

<class 'pandas.core.frame.DataFrame'>
Index: 869 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  869 non-null    int64
 1   Survived     869 non-null    int64
 2   Pclass       869 non-null    int64
 3   Name         869 non-null    object
 4   Sex          869 non-null    int64
 5   Age          700 non-null    float64
 6   SibSp        869 non-null    int64
 7   Parch        869 non-null    int64
 8   Ticket       869 non-null    object
 9   Fare         869 non-null    float64
 10  Cabin        200 non-null    object
 11  Embarked     867 non-null    object
 12  filled_Age   869 non-null    float64
 13  Family_Size  869 non-null    int64
 14  FamilySize   869 non-null    int64
dtypes: float64(3), int64(8), object(4)
memory usage: 108.6+ KB